#pragma once

typedef enum {
	OWNER_FREE                = 0,
	OWNER_PWMINPUT,
	OWNER_PPMINPUT,
	OWNER_PWMOUTPUT_MOTOR,
	OWNER_PWMOUTPUT_FAST,
	OWNER_PWMOUTPUT_ONESHOT,
	OWNER_PWMOUTPUT_SERVO,
	OWNER_SOFTSERIAL_RX,
	OWNER_SOFTSERIAL_TX,
	OWNER_SOFTSERIAL_RXTX,        
	OWNER_SOFTSERIAL_AUXTIMER,    
	OWNER_ADC,
	OWNER_SERIAL_RX,
	OWNER_SERIAL_TX,
	OWNER_SERIAL_RXTX,
	OWNER_PINDEBUG,
	OWNER_TIMER,
	OWNER_SONAR,
	OWNER_SYSTEM,
} resourceOwner_t;




typedef enum {
	RESOURCE_INPUT      = 1 << 0,
	RESOURCE_OUTPUT     = 1 << 1,
	RESOURCE_IO         = RESOURCE_INPUT | RESOURCE_OUTPUT,
	RESOURCE_TIMER      = 1 << 2,
	RESOURCE_TIMER_DUAL = 1 << 3, 
	RESOURCE_USART      = 1 << 4,
	RESOURCE_ADC        = 1 << 5,
	RESOURCE_EXTI       = 1 << 6,
    RESOURCE_I2C        = 1 << 7,
    RESOURCE_SPI        = 1 << 8,
} resourceType_t;
